// ── Risky Civ — Game Configuration (AUTO-GENERATED) ─────────────────
// DO NOT EDIT THIS FILE DIRECTLY.
// Edit server/config.js instead, then run: npm run sync
// ─────────────────────────────────────────────────────────────────────

export const PLAYER_COLORS = [
  "#4A90D9",
  "#D94A4A"
];

export const PLAYER_NAMES = [
  "Player",
  "AI"
];

export const NEUTRAL_COLOR = "#8B8B8B";

export const RESOURCE_TYPES = [
  "production",
  "research",
  "money"
];

export const STARTING_RESOURCES = {
  "production": 10,
  "research": 0,
  "money": 15
};

export const BASE_TERRITORY_RESOURCES = {
  "production": 1,
  "research": 1,
  "money": 1
};

export const STRUCTURES = {
  "factory": {
    "name": "Factory",
    "icon": "🏭",
    "cost": {
      "production": 5,
      "money": 3
    },
    "bonus": {
      "production": 2
    }
  },
  "university": {
    "name": "University",
    "icon": "🎓",
    "cost": {
      "production": 3,
      "money": 5
    },
    "bonus": {
      "research": 2
    }
  },
  "bank": {
    "name": "Bank",
    "icon": "🏦",
    "cost": {
      "production": 3,
      "money": 4
    },
    "bonus": {
      "money": 2
    }
  }
};

export const TROOP_DEPLOY_COST = 3;

export const TROOP_UPKEEP_COST = 1;

export const BASE_DEPLOY_COUNT = 3;

export const MIN_GARRISON = 1;

export const BASE_ACTIONS_PER_TURN = 3;

export const MAX_ATTACK_DICE = 3;

export const MAX_DEFEND_DICE = 2;

export const DICE_SIDES = 6;

export const STARTING_HAND_SIZE = 7;

export const MAX_HAND_SIZE = 7;

export const CARDS_DRAWN_PER_TURN = 1;

export const WIN_TERRITORY_PERCENT = 0.75;

export const TOTAL_TERRITORIES = 30;

export const BONUS_CARDS = [
  {
    "id": "prod_01",
    "name": "Industrial Revolution",
    "category": "production",
    "type": "bonus",
    "cost": 30,
    "description": "All factories produce double this turn.",
    "icon": "🏭"
  },
  {
    "id": "prod_02",
    "name": "Free Construction",
    "category": "production",
    "type": "bonus",
    "cost": 18,
    "description": "Build one structure for free.",
    "icon": "🔨"
  },
  {
    "id": "prod_03",
    "name": "Supply Surge",
    "category": "production",
    "type": "bonus",
    "cost": 24,
    "description": "Gain +15 Production immediately.",
    "icon": "📦"
  },
  {
    "id": "prod_04",
    "name": "Overtime Workers",
    "category": "production",
    "type": "bonus",
    "cost": 12,
    "description": "Gain +8 Production immediately.",
    "icon": "👷"
  },
  {
    "id": "prod_05",
    "name": "Mass Production",
    "category": "production",
    "type": "bonus",
    "cost": 24,
    "description": "Deploy troops at half cost this turn.",
    "icon": "🔧"
  },
  {
    "id": "prod_06",
    "name": "Harvest Festival",
    "category": "production",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +5 of each resource.",
    "icon": "🎉"
  },
  {
    "id": "prod_07",
    "name": "Iron Mine",
    "category": "production",
    "type": "bonus",
    "cost": 12,
    "description": "Gain +6 Production immediately.",
    "icon": "⛏️"
  },
  {
    "id": "prod_08",
    "name": "Assembly Line",
    "category": "production",
    "type": "bonus",
    "cost": 30,
    "description": "Gain +20 Production immediately.",
    "icon": "🏗️"
  },
  {
    "id": "prod_09",
    "name": "Salvage Operation",
    "category": "production",
    "type": "bonus",
    "cost": 6,
    "description": "Gain +4 Production immediately.",
    "icon": "♻️"
  },
  {
    "id": "prod_10",
    "name": "Resource Convoy",
    "category": "production",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +10 Production immediately.",
    "icon": "🚛"
  },
  {
    "id": "prod_11",
    "name": "Wartime Economy",
    "category": "production",
    "type": "bonus",
    "cost": 24,
    "description": "Convert 10 Money into 15 Production.",
    "icon": "⚙️"
  },
  {
    "id": "prod_12",
    "name": "Blueprint Cache",
    "category": "production",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +5 Production and +5 Research.",
    "icon": "📐"
  },
  {
    "id": "res_01",
    "name": "Eureka Moment",
    "category": "research",
    "type": "bonus",
    "cost": 24,
    "description": "Gain +15 Research immediately.",
    "icon": "💡"
  },
  {
    "id": "res_02",
    "name": "Stolen Blueprints",
    "category": "research",
    "type": "bonus",
    "cost": 27,
    "description": "Steal 10 Research from the enemy.",
    "icon": "📜"
  },
  {
    "id": "res_03",
    "name": "Think Tank",
    "category": "research",
    "type": "bonus",
    "cost": 18,
    "description": "Universities produce double this turn.",
    "icon": "🧠"
  },
  {
    "id": "res_04",
    "name": "Academic Exchange",
    "category": "research",
    "type": "bonus",
    "cost": 15,
    "description": "Gain +10 Research immediately.",
    "icon": "📚"
  },
  {
    "id": "res_05",
    "name": "Innovation Grant",
    "category": "research",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +8 Research and draw a card.",
    "icon": "🏅"
  },
  {
    "id": "res_06",
    "name": "Laboratory",
    "category": "research",
    "type": "bonus",
    "cost": 9,
    "description": "Gain +6 Research immediately.",
    "icon": "🔬"
  },
  {
    "id": "res_07",
    "name": "Breakthrough",
    "category": "research",
    "type": "bonus",
    "cost": 24,
    "description": "Gain +18 Research immediately.",
    "icon": "⚡"
  },
  {
    "id": "res_08",
    "name": "Knowledge Transfer",
    "category": "research",
    "type": "bonus",
    "cost": 15,
    "description": "Convert 8 Money into 12 Research.",
    "icon": "🎓"
  },
  {
    "id": "res_09",
    "name": "Patent Office",
    "category": "research",
    "type": "bonus",
    "cost": 6,
    "description": "Gain +4 Research immediately.",
    "icon": "📋"
  },
  {
    "id": "res_10",
    "name": "Research Expedition",
    "category": "research",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +12 Research immediately.",
    "icon": "🧭"
  },
  {
    "id": "res_11",
    "name": "Science Fair",
    "category": "research",
    "type": "bonus",
    "cost": 9,
    "description": "Gain +5 Research per University you own.",
    "icon": "🏆"
  },
  {
    "id": "res_12",
    "name": "Ancient Library",
    "category": "research",
    "type": "bonus",
    "cost": 15,
    "description": "Gain +8 Research and +4 Production.",
    "icon": "📖"
  },
  {
    "id": "mon_01",
    "name": "Tax Collection",
    "category": "money",
    "type": "bonus",
    "cost": 18,
    "description": "Collect 3 Money per territory you own.",
    "icon": "💰"
  },
  {
    "id": "mon_02",
    "name": "Economic Boom",
    "category": "money",
    "type": "bonus",
    "cost": 30,
    "description": "Gain +20 Money immediately.",
    "icon": "📈"
  },
  {
    "id": "mon_03",
    "name": "Trade Agreement",
    "category": "money",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +12 Money immediately.",
    "icon": "🤝"
  },
  {
    "id": "mon_04",
    "name": "Gold Rush",
    "category": "money",
    "type": "bonus",
    "cost": 24,
    "description": "Banks produce double this turn.",
    "icon": "💎"
  },
  {
    "id": "mon_05",
    "name": "Foreign Investment",
    "category": "money",
    "type": "bonus",
    "cost": 12,
    "description": "Gain +8 Money immediately.",
    "icon": "🏦"
  },
  {
    "id": "mon_06",
    "name": "War Chest",
    "category": "money",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +10 Money and +5 Production.",
    "icon": "🗃️"
  },
  {
    "id": "mon_07",
    "name": "Treasure Map",
    "category": "money",
    "type": "bonus",
    "cost": 12,
    "description": "Gain +15 Money.",
    "icon": "🗺️"
  },
  {
    "id": "mon_08",
    "name": "Market Manipulation",
    "category": "money",
    "type": "bonus",
    "cost": 24,
    "description": "Steal 8 Money from the enemy.",
    "icon": "🎭"
  },
  {
    "id": "mon_09",
    "name": "Trade Caravan",
    "category": "money",
    "type": "bonus",
    "cost": 6,
    "description": "Gain +5 Money immediately.",
    "icon": "🐫"
  },
  {
    "id": "mon_10",
    "name": "Royal Treasury",
    "category": "money",
    "type": "bonus",
    "cost": 30,
    "description": "Gain +25 Money immediately.",
    "icon": "👑"
  },
  {
    "id": "mon_11",
    "name": "Merchant Fleet",
    "category": "money",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +4 Money per Bank you own.",
    "icon": "⛵"
  },
  {
    "id": "mon_12",
    "name": "Loan Shark",
    "category": "money",
    "type": "bonus",
    "cost": 0,
    "description": "Gain +12 Money but lose 5 Production.",
    "icon": "🦈"
  },
  {
    "id": "mil_01",
    "name": "Paradrop",
    "category": "military",
    "type": "bonus",
    "cost": 36,
    "description": "Deploy 5 troops to any territory you own.",
    "icon": "🪂"
  },
  {
    "id": "mil_02",
    "name": "Mutiny",
    "category": "military",
    "type": "bonus",
    "cost": 30,
    "description": "Enemy weakest territory loses half its troops.",
    "icon": "🏴"
  },
  {
    "id": "mil_03",
    "name": "Forced March",
    "category": "military",
    "type": "bonus",
    "cost": 18,
    "description": "Move up to 5 troops between adjacent owned territories.",
    "icon": "🚩"
  },
  {
    "id": "mil_04",
    "name": "Veteran Troops",
    "category": "military",
    "type": "bonus",
    "cost": 24,
    "description": "+1 to all attack dice this turn.",
    "icon": "🎖️"
  },
  {
    "id": "mil_05",
    "name": "Conscription",
    "category": "military",
    "type": "bonus",
    "cost": 18,
    "description": "Deploy 3 troops for free to your capital.",
    "icon": "📯"
  },
  {
    "id": "mil_06",
    "name": "Fortify",
    "category": "military",
    "type": "bonus",
    "cost": 18,
    "description": "+1 to all defense dice this turn.",
    "icon": "🛡️"
  },
  {
    "id": "mil_07",
    "name": "Mercenaries",
    "category": "military",
    "type": "bonus",
    "cost": 36,
    "description": "Deploy 4 troops for free to any territory.",
    "icon": "💂"
  },
  {
    "id": "mil_08",
    "name": "Alliance",
    "category": "military",
    "type": "bonus",
    "cost": 30,
    "description": "Gain +4 troops in a territory of your choice.",
    "icon": "🤝"
  },
  {
    "id": "mil_09",
    "name": "Spy Network",
    "category": "military",
    "type": "bonus",
    "cost": 36,
    "description": "Steal one card from enemy hand.",
    "icon": "🕵️"
  },
  {
    "id": "mil_10",
    "name": "Ambush",
    "category": "military",
    "type": "bonus",
    "cost": 24,
    "description": "+2 to your highest attack die this turn.",
    "icon": "🏹"
  },
  {
    "id": "mil_11",
    "name": "Garrison Reinforcement",
    "category": "military",
    "type": "bonus",
    "cost": 12,
    "description": "Add +2 troops to all territories with 1 troop.",
    "icon": "🏰"
  },
  {
    "id": "mil_12",
    "name": "War Banner",
    "category": "military",
    "type": "bonus",
    "cost": 18,
    "description": "Deploy 2 free troops to your 3 weakest territories.",
    "icon": "🚩"
  },
  {
    "id": "multi_01",
    "name": "Golden Age",
    "category": "multi",
    "type": "bonus",
    "cost": 30,
    "description": "Gain +8 of each resource.",
    "icon": "🌟"
  },
  {
    "id": "multi_02",
    "name": "Bountiful Harvest",
    "category": "multi",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +5 of each resource.",
    "icon": "🌾"
  },
  {
    "id": "multi_03",
    "name": "Diplomatic Victory",
    "category": "multi",
    "type": "bonus",
    "cost": 30,
    "description": "An unclaimed territory joins you with 2 troops.",
    "icon": "🕊️"
  },
  {
    "id": "multi_04",
    "name": "Refugees",
    "category": "multi",
    "type": "bonus",
    "cost": 12,
    "description": "Gain +3 troops in your weakest territory.",
    "icon": "🏕️"
  },
  {
    "id": "multi_05",
    "name": "Festival",
    "category": "multi",
    "type": "bonus",
    "cost": 12,
    "description": "Gain +4 of each resource.",
    "icon": "🎊"
  },
  {
    "id": "multi_06",
    "name": "Peace Treaty",
    "category": "multi",
    "type": "bonus",
    "cost": 24,
    "description": "Gain +10 Money and +10 Research.",
    "icon": "📜"
  },
  {
    "id": "multi_07",
    "name": "Cultural Exchange",
    "category": "multi",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +6 Research and +6 Money.",
    "icon": "🎭"
  },
  {
    "id": "multi_08",
    "name": "Nationalization",
    "category": "multi",
    "type": "bonus",
    "cost": 24,
    "description": "Gain +3 of each resource per Factory you own.",
    "icon": "🏛️"
  },
  {
    "id": "multi_09",
    "name": "War Bonds",
    "category": "multi",
    "type": "bonus",
    "cost": 6,
    "description": "Gain +3 Production and +3 Money.",
    "icon": "📃"
  },
  {
    "id": "multi_10",
    "name": "Prosperity",
    "category": "multi",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +7 Production and +7 Money.",
    "icon": "🌈"
  },
  {
    "id": "multi_11",
    "name": "Expeditionary Force",
    "category": "multi",
    "type": "bonus",
    "cost": 30,
    "description": "Deploy 3 troops and gain +8 Production.",
    "icon": "⚓"
  },
  {
    "id": "multi_12",
    "name": "Windfall",
    "category": "multi",
    "type": "bonus",
    "cost": 6,
    "description": "Gain +3 of each resource.",
    "icon": "🍀"
  },
  {
    "id": "mil_ex01",
    "name": "Blitzkrieg",
    "category": "military",
    "type": "bonus",
    "cost": 36,
    "description": "Attack one territory for free (costs 0 actions).",
    "icon": "⚡"
  },
  {
    "id": "mil_ex02",
    "name": "Scorched Earth",
    "category": "military",
    "type": "bonus",
    "cost": 30,
    "description": "Destroy all structures in a selected enemy territory.",
    "icon": "🔥"
  },
  {
    "id": "mil_ex03",
    "name": "Draft",
    "category": "military",
    "type": "bonus",
    "cost": 24,
    "description": "Gain +1 troop in every territory you own.",
    "icon": "🪖"
  },
  {
    "id": "mil_ex04",
    "name": "Naval Blockade",
    "category": "military",
    "type": "bonus",
    "cost": 30,
    "description": "Enemy cannot attack across sea routes on their next turn.",
    "icon": "⚓"
  },
  {
    "id": "prod_ex01",
    "name": "Supply Chain Optimization",
    "category": "production",
    "type": "bonus",
    "cost": 24,
    "description": "Treat all structures as costing 0 production this turn.",
    "icon": "📦"
  },
  {
    "id": "prod_ex02",
    "name": "Deforestation",
    "category": "production",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +30 Production immediately, but effectively lose 1 Money income from your Capital permanently.",
    "icon": "🪓"
  },
  {
    "id": "prod_ex03",
    "name": "Urban Sprawl",
    "category": "production",
    "type": "bonus",
    "cost": 36,
    "description": "Build up to 2 structures of any type for free.",
    "icon": "🏙️"
  },
  {
    "id": "res_ex01",
    "name": "Brain Drain",
    "category": "research",
    "type": "bonus",
    "cost": 24,
    "description": "Steal 20 Research from the enemy.",
    "icon": "🧠"
  },
  {
    "id": "res_ex02",
    "name": "Reverse Engineering",
    "category": "research",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +30 Research if the enemy has more tech unlocked than you.",
    "icon": "🔧"
  },
  {
    "id": "res_ex03",
    "name": "Space Program",
    "category": "research",
    "type": "bonus",
    "cost": 36,
    "description": "Gain +50 Research immediately.",
    "icon": "🚀"
  },
  {
    "id": "mon_ex01",
    "name": "Billionaire Benefactor",
    "category": "money",
    "type": "bonus",
    "cost": 0,
    "description": "Gain +40 Money immediately, but skip your next Card Draw phase.",
    "icon": "🎩"
  },
  {
    "id": "mon_ex02",
    "name": "War Profiteering",
    "category": "money",
    "type": "bonus",
    "cost": 18,
    "description": "Gain +10 Money for every territory you captured this turn.",
    "icon": "💹"
  }
];

export const EVENT_CARDS = [
  {
    "id": "evt_01",
    "name": "Plague",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All players lose 2 troops from their most populated territory.",
    "icon": "☠️"
  },
  {
    "id": "evt_02",
    "name": "Earthquake",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "A random structure is destroyed for each player.",
    "icon": "🌋"
  },
  {
    "id": "evt_03",
    "name": "Recession",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All players lose 30% of their Money.",
    "icon": "📉"
  },
  {
    "id": "evt_04",
    "name": "Famine",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All players lose 8 Production.",
    "icon": "🥀"
  },
  {
    "id": "evt_05",
    "name": "Civil Unrest",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All players lose 1 troop in every territory.",
    "icon": "🔥"
  },
  {
    "id": "evt_06",
    "name": "Desertion",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All players lose 2 troops in their weakest territory.",
    "icon": "🏳️"
  },
  {
    "id": "evt_07",
    "name": "Corruption",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All players lose 5 Money and 3 Production.",
    "icon": "🐀"
  },
  {
    "id": "evt_08",
    "name": "Arms Race",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All players gain +3 troops to their capital but lose 10 Money.",
    "icon": "🚀"
  },
  {
    "id": "evt_09",
    "name": "Meteor Shower",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All players lose a random structure and 2 troops from their strongest territory.",
    "icon": "☄️"
  },
  {
    "id": "evt_10",
    "name": "Embargo",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All players' Banks produce nothing this turn.",
    "icon": "🚢"
  },
  {
    "id": "evt_11",
    "name": "Golden Age",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "Both players gain +40 to all resources (Production, Research, Money).",
    "icon": "🌟"
  },
  {
    "id": "evt_12",
    "name": "Cyberattack",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "All technology effects are temporarily disabled for 1 turn.",
    "icon": "💻"
  },
  {
    "id": "evt_13",
    "name": "Pandemic",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "Both players lose 30% of their troops across all territories.",
    "icon": "☣️"
  },
  {
    "id": "evt_14",
    "name": "Economic Crash",
    "category": "event",
    "type": "event",
    "cost": 0,
    "description": "Both players lose 100% of their currently banked Money.",
    "icon": "📉"
  }
];

export const TECH_TREE = {
  "military": [
    {
      "id": "mil_t1",
      "name": "Sharpened Blades",
      "cost": 15,
      "description": "+1 to highest attack die",
      "effect": "attackBonus"
    },
    {
      "id": "mil_t2",
      "name": "Fortified Walls",
      "cost": 30,
      "description": "+1 to highest defense die",
      "effect": "defenseBonus"
    },
    {
      "id": "mil_t3",
      "name": "Double Deploy",
      "cost": 53,
      "description": "Deploy action gives 2× troops",
      "effect": "doubleDeploy"
    },
    {
      "id": "mil_t4",
      "name": "Elite Troops",
      "cost": 75,
      "description": "Troops cost 50% less to deploy",
      "effect": "eliteTroops"
    },
    {
      "id": "mil_t5",
      "name": "Naval Supremacy",
      "cost": 60,
      "description": "Attack across sea routes between continents",
      "effect": "intercontinentalCombat"
    },
    {
      "id": "mil_t6",
      "name": "Siege Tactics",
      "cost": 90,
      "description": "Ignore target's \"Fortify\" and structure defensive bonuses when attacking",
      "effect": "siegeTactics"
    },
    {
      "id": "mil_t7",
      "name": "Guerilla Warfare",
      "cost": 113,
      "description": "When defending, guaranteed to inflict at least 1 casualty",
      "effect": "guerillaWarfare"
    },
    {
      "id": "mil_t8",
      "name": "Combined Arms",
      "cost": 150,
      "description": "Attack with up to 5 dice instead of 3",
      "effect": "combinedArms"
    }
  ],
  "economic": [
    {
      "id": "eco_t1",
      "name": "Improved Structures",
      "cost": 15,
      "description": "Structures give +1 extra bonus",
      "effect": "betterStructures"
    },
    {
      "id": "eco_t2",
      "name": "Prosperous Lands",
      "cost": 30,
      "description": "Base territory output +1 each",
      "effect": "betterBase"
    },
    {
      "id": "eco_t3",
      "name": "Rapid Construction",
      "cost": 53,
      "description": "Build action constructs 2 structures",
      "effect": "rapidConstruction"
    },
    {
      "id": "eco_t4",
      "name": "Trade Routes",
      "cost": 75,
      "description": "Continent bonuses doubled",
      "effect": "tradeRoutes"
    },
    {
      "id": "eco_t5",
      "name": "Banking Guild",
      "cost": 90,
      "description": "All Banks provide +4 Money instead of +2",
      "effect": "bankingGuild"
    },
    {
      "id": "eco_t6",
      "name": "Tax Havens",
      "cost": 120,
      "description": "Troop upkeep costs permanently reduced to 0.5 per troop",
      "effect": "taxHavens"
    },
    {
      "id": "eco_t7",
      "name": "Industrial Espionage",
      "cost": 150,
      "description": "Passively gain resources equal to 10% of enemy's income each turn",
      "effect": "industrialEspionage"
    }
  ],
  "science": [
    {
      "id": "sci_t1",
      "name": "Expanded Library",
      "cost": 15,
      "description": "Draw 2 cards per turn instead of 1",
      "effect": "extraDraw"
    },
    {
      "id": "sci_t2",
      "name": "Efficient Planning",
      "cost": 30,
      "description": "Gain a 4th action per turn",
      "effect": "extraAction"
    },
    {
      "id": "sci_t3",
      "name": "Advanced Tactics",
      "cost": 53,
      "description": "Can attack with 4 dice",
      "effect": "fourDice"
    },
    {
      "id": "sci_t5",
      "name": "Logistics Network",
      "cost": 90,
      "description": "Max actions increased from 4 to 5 per turn",
      "effect": "logisticsNetwork"
    },
    {
      "id": "sci_t6",
      "name": "Scientific Method",
      "cost": 120,
      "description": "Base research output from all sources is doubled",
      "effect": "scientificMethod"
    },
    {
      "id": "sci_t8",
      "name": "World Domination",
      "cost": 225,
      "description": "Instant victory — you win!",
      "effect": "worldDomination"
    }
  ]
};

// Combined alias (client-only convenience export)
export const CARD_DEFINITIONS = [...BONUS_CARDS, ...EVENT_CARDS];
